name: Build Flutter + Rust (ARM64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Install build deps
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libayatana-appindicator3-dev patchelf clang cmake ninja-build pkg-config liblzma-dev curl

      - name: Build Flutter .deb
        run: |
          flutter pub get
          flutter build deb --target-platform=linux-arm64

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: venera-linux-arm64
          path: build/linux/arm64/release/bundle
